/**
 * The order the children of one element go in, per parent.
 *
 * A writer that swaps one child of a formatting fragment has to put a child that was not there
 * into the spot the format lays down, and `wml.xsd` is what lays it down. Each entry below names
 * the complex type it mirrors, and `childOrder.test.ts` reads that type out of the committed
 * schema and compares it, so an entry cannot drift from the format it claims to follow.
 *
 * Where the type is a sequence the order is the schema's and nothing else. Where it is a choice
 * the schema fixes no order among the alternatives, so the order here is this package's
 * convention: the schema's own document order. Mutually exclusive alternatives (a content
 * control's type, a cell's markup record) are listed in that same order, since only one of them
 * can ever stand there.
 *
 * A name is the local part alone, as `Props` carries it, which is also how the two children
 * `w:settings` takes from other namespaces (`m:mathPr`, `sl:schemaLibrary`) are spelled here.
 */

interface ChildOrder {
  readonly type: string;
  readonly order: readonly string[];
}

export const CHILD_ORDER: Readonly<Record<string, ChildOrder>> = {
  // EG_RPrBase's choice, then rPrChange
  rPr: {
    type: "CT_RPr",
    order: [
      "rStyle",
      "rFonts",
      "b",
      "bCs",
      "i",
      "iCs",
      "caps",
      "smallCaps",
      "strike",
      "dstrike",
      "outline",
      "shadow",
      "emboss",
      "imprint",
      "noProof",
      "snapToGrid",
      "vanish",
      "webHidden",
      "color",
      "spacing",
      "w",
      "kern",
      "position",
      "sz",
      "szCs",
      "highlight",
      "u",
      "effect",
      "bdr",
      "shd",
      "fitText",
      "vertAlign",
      "rtl",
      "cs",
      "em",
      "lang",
      "eastAsianLayout",
      "specVanish",
      "oMath",
      "rPrChange",
    ],
  },
  // the track-change record first, then EG_RPrBase's choice
  "pPr/rPr": {
    type: "CT_ParaRPr",
    order: [
      "ins",
      "del",
      "moveFrom",
      "moveTo",
      "rStyle",
      "rFonts",
      "b",
      "bCs",
      "i",
      "iCs",
      "caps",
      "smallCaps",
      "strike",
      "dstrike",
      "outline",
      "shadow",
      "emboss",
      "imprint",
      "noProof",
      "snapToGrid",
      "vanish",
      "webHidden",
      "color",
      "spacing",
      "w",
      "kern",
      "position",
      "sz",
      "szCs",
      "highlight",
      "u",
      "effect",
      "bdr",
      "shd",
      "fitText",
      "vertAlign",
      "rtl",
      "cs",
      "em",
      "lang",
      "eastAsianLayout",
      "specVanish",
      "oMath",
      "rPrChange",
    ],
  },
  pPr: {
    type: "CT_PPr",
    order: [
      "pStyle",
      "keepNext",
      "keepLines",
      "pageBreakBefore",
      "framePr",
      "widowControl",
      "numPr",
      "suppressLineNumbers",
      "pBdr",
      "shd",
      "tabs",
      "suppressAutoHyphens",
      "kinsoku",
      "wordWrap",
      "overflowPunct",
      "topLinePunct",
      "autoSpaceDE",
      "autoSpaceDN",
      "bidi",
      "adjustRightInd",
      "snapToGrid",
      "spacing",
      "ind",
      "contextualSpacing",
      "mirrorIndents",
      "suppressOverlap",
      "jc",
      "textDirection",
      "textAlignment",
      "textboxTightWrap",
      "outlineLvl",
      "divId",
      "cnfStyle",
      "rPr",
      "sectPr",
      "pPrChange",
    ],
  },
  tcPr: {
    type: "CT_TcPr",
    order: [
      "cnfStyle",
      "tcW",
      "gridSpan",
      "hMerge",
      "vMerge",
      "tcBorders",
      "shd",
      "noWrap",
      "tcMar",
      "textDirection",
      "tcFitText",
      "vAlign",
      "hideMark",
      "headers",
      "cellIns",
      "cellDel",
      "cellMerge",
      "tcPrChange",
    ],
  },
  // CT_TrPrBase's choice, then the track-change record
  trPr: {
    type: "CT_TrPr",
    order: [
      "cnfStyle",
      "divId",
      "gridBefore",
      "gridAfter",
      "wBefore",
      "wAfter",
      "cantSplit",
      "trHeight",
      "tblHeader",
      "tblCellSpacing",
      "jc",
      "hidden",
      "ins",
      "del",
      "trPrChange",
    ],
  },
  tblPr: {
    type: "CT_TblPr",
    order: [
      "tblStyle",
      "tblpPr",
      "tblOverlap",
      "bidiVisual",
      "tblStyleRowBandSize",
      "tblStyleColBandSize",
      "tblW",
      "jc",
      "tblCellSpacing",
      "tblInd",
      "tblBorders",
      "shd",
      "tblLayout",
      "tblCellMar",
      "tblLook",
      "tblCaption",
      "tblDescription",
      "tblPrChange",
    ],
  },
  tcBorders: {
    type: "CT_TcBorders",
    order: [
      "top",
      "start",
      "left",
      "bottom",
      "end",
      "right",
      "insideH",
      "insideV",
      "tl2br",
      "tr2bl",
    ],
  },
  tblBorders: {
    type: "CT_TblBorders",
    order: [
      "top",
      "start",
      "left",
      "bottom",
      "end",
      "right",
      "insideH",
      "insideV",
    ],
  },
  pBdr: {
    type: "CT_PBdr",
    order: ["top", "left", "bottom", "right", "between", "bar"],
  },
  tcMar: {
    type: "CT_TcMar",
    order: ["top", "start", "left", "bottom", "end", "right"],
  },
  tblCellMar: {
    type: "CT_TblCellMar",
    order: ["top", "start", "left", "bottom", "end", "right"],
  },
  // CT_SdtRun lays the same three down
  sdt: {
    type: "CT_SdtBlock",
    order: ["sdtPr", "sdtEndPr", "sdtContent"],
  },
  sdtPr: {
    type: "CT_SdtPr",
    order: [
      "rPr",
      "alias",
      "tag",
      "id",
      "lock",
      "placeholder",
      "temporary",
      "showingPlcHdr",
      "dataBinding",
      "label",
      "tabIndex",
      "equation",
      "comboBox",
      "date",
      "docPartObj",
      "docPartList",
      "dropDownList",
      "picture",
      "richText",
      "text",
      "citation",
      "group",
      "bibliography",
    ],
  },
  sectPr: {
    type: "CT_SectPr",
    order: [
      "headerReference",
      "footerReference",
      "footnotePr",
      "endnotePr",
      "type",
      "pgSz",
      "pgMar",
      "paperSrc",
      "pgBorders",
      "lnNumType",
      "pgNumType",
      "cols",
      "formProt",
      "vAlign",
      "noEndnote",
      "titlePg",
      "textDirection",
      "bidi",
      "rtlGutter",
      "docGrid",
      "printerSettings",
      "sectPrChange",
    ],
  },
  numPr: {
    type: "CT_NumPr",
    order: ["ilvl", "numId", "numberingChange", "ins"],
  },
  lvl: {
    type: "CT_Lvl",
    order: [
      "start",
      "numFmt",
      "lvlRestart",
      "pStyle",
      "isLgl",
      "suff",
      "lvlText",
      "lvlPicBulletId",
      "legacy",
      "lvlJc",
      "pPr",
      "rPr",
    ],
  },
  abstractNum: {
    type: "CT_AbstractNum",
    order: [
      "nsid",
      "multiLevelType",
      "tmpl",
      "name",
      "styleLink",
      "numStyleLink",
      "lvl",
    ],
  },
  num: {
    type: "CT_Num",
    order: ["abstractNumId", "lvlOverride"],
  },
  numbering: {
    type: "CT_Numbering",
    order: ["numPicBullet", "abstractNum", "num", "numIdMacAtCleanup"],
  },
  tblStylePr: {
    type: "CT_TblStylePr",
    order: ["pPr", "rPr", "tblPr", "trPr", "tcPr"],
  },
  style: {
    type: "CT_Style",
    order: [
      "name",
      "aliases",
      "basedOn",
      "next",
      "link",
      "autoRedefine",
      "hidden",
      "uiPriority",
      "semiHidden",
      "unhideWhenUsed",
      "qFormat",
      "locked",
      "personal",
      "personalCompose",
      "personalReply",
      "rsid",
      "pPr",
      "rPr",
      "tblPr",
      "trPr",
      "tcPr",
      "tblStylePr",
    ],
  },
  settings: {
    type: "CT_Settings",
    order: [
      "writeProtection",
      "view",
      "zoom",
      "removePersonalInformation",
      "removeDateAndTime",
      "doNotDisplayPageBoundaries",
      "displayBackgroundShape",
      "printPostScriptOverText",
      "printFractionalCharacterWidth",
      "printFormsData",
      "embedTrueTypeFonts",
      "embedSystemFonts",
      "saveSubsetFonts",
      "saveFormsData",
      "mirrorMargins",
      "alignBordersAndEdges",
      "bordersDoNotSurroundHeader",
      "bordersDoNotSurroundFooter",
      "gutterAtTop",
      "hideSpellingErrors",
      "hideGrammaticalErrors",
      "activeWritingStyle",
      "proofState",
      "formsDesign",
      "attachedTemplate",
      "linkStyles",
      "stylePaneFormatFilter",
      "stylePaneSortMethod",
      "documentType",
      "mailMerge",
      "revisionView",
      "trackRevisions",
      "doNotTrackMoves",
      "doNotTrackFormatting",
      "documentProtection",
      "autoFormatOverride",
      "styleLockTheme",
      "styleLockQFSet",
      "defaultTabStop",
      "autoHyphenation",
      "consecutiveHyphenLimit",
      "hyphenationZone",
      "doNotHyphenateCaps",
      "showEnvelope",
      "summaryLength",
      "clickAndTypeStyle",
      "defaultTableStyle",
      "evenAndOddHeaders",
      "bookFoldRevPrinting",
      "bookFoldPrinting",
      "bookFoldPrintingSheets",
      "drawingGridHorizontalSpacing",
      "drawingGridVerticalSpacing",
      "displayHorizontalDrawingGridEvery",
      "displayVerticalDrawingGridEvery",
      "doNotUseMarginsForDrawingGridOrigin",
      "drawingGridHorizontalOrigin",
      "drawingGridVerticalOrigin",
      "doNotShadeFormData",
      "noPunctuationKerning",
      "characterSpacingControl",
      "printTwoOnOne",
      "strictFirstAndLastChars",
      "noLineBreaksAfter",
      "noLineBreaksBefore",
      "savePreviewPicture",
      "doNotValidateAgainstSchema",
      "saveInvalidXml",
      "ignoreMixedContent",
      "alwaysShowPlaceholderText",
      "doNotDemarcateInvalidXml",
      "saveXmlDataOnly",
      "useXSLTWhenSaving",
      "saveThroughXslt",
      "showXMLTags",
      "alwaysMergeEmptyNamespace",
      "updateFields",
      "hdrShapeDefaults",
      "footnotePr",
      "endnotePr",
      "compat",
      "docVars",
      "rsids",
      "mathPr",
      "attachedSchema",
      "themeFontLang",
      "clrSchemeMapping",
      "doNotIncludeSubdocsInStats",
      "doNotAutoCompressPictures",
      "forceUpgrade",
      "captions",
      "readModeInkLockDown",
      "smartTagType",
      "schemaLibrary",
      "shapeDefaults",
      "doNotEmbedSmartTags",
      "decimalSymbol",
      "listSeparator",
    ],
  },
};

/**
 * The order the children of this parent go in.
 *
 * A nested parent is asked for first (`pPr/rPr` is CT_ParaRPr, which puts a track-change record
 * ahead of what a run's own `w:rPr` holds), so naming the enclosing element is what picks the
 * right one of two entries for the same element name.
 *
 * Throws for a parent no entry covers, because a writer editing an element this registry has
 * never seen would otherwise place its children by nothing at all.
 */
export function childOrderOf(name: string, parent?: string): readonly string[] {
  const nested =
    parent === undefined ? undefined : CHILD_ORDER[`${parent}/${name}`];
  const order = nested ?? CHILD_ORDER[name];
  if (!order) {
    throw new Error(
      `no child order is registered for ${name}; add it to CHILD_ORDER`
    );
  }
  return order.order;
}
