/**
 * The order the children of one element go in, per parent.
 *
 * A writer that swaps one child of a formatting fragment has to put a child that was not there
 * into the spot the format lays down, and `wml.xsd` is what lays it down. Each entry below names
 * the complex type it mirrors, and `childOrder.test.ts` reads that type out of the committed
 * schema and compares it, so an entry cannot drift from the format it claims to follow.
 *
 * Where the type is a sequence the order is the schema's and nothing else. Where it is a choice
 * the schema fixes no order among the alternatives, so the order here is this package's
 * convention: the schema's own document order, which is also what Word writes. Alternatives that
 * exclude one another (a content control's type, a cell's markup record) are listed in that same
 * order for the same reason, since only one of them can ever stand there.
 *
 * A name is the local part alone, as `Props` carries it, which is also how the two children
 * `w:settings` takes from other namespaces (`m:mathPr`, `sl:schemaLibrary`) are spelled here.
 */

export const CHILD_ORDER: Readonly<Record<string, readonly string[]>> = {
  // CT_RPr: EG_RPrBase's choice, then rPrChange
  rPr: [
    "rStyle",
    "rFonts",
    "b",
    "bCs",
    "i",
    "iCs",
    "caps",
    "smallCaps",
    "strike",
    "dstrike",
    "outline",
    "shadow",
    "emboss",
    "imprint",
    "noProof",
    "snapToGrid",
    "vanish",
    "webHidden",
    "color",
    "spacing",
    "w",
    "kern",
    "position",
    "sz",
    "szCs",
    "highlight",
    "u",
    "effect",
    "bdr",
    "shd",
    "fitText",
    "vertAlign",
    "rtl",
    "cs",
    "em",
    "lang",
    "eastAsianLayout",
    "specVanish",
    "oMath",
    "rPrChange",
  ],
  // CT_ParaRPr: the track-change record first, then EG_RPrBase's choice
  "pPr/rPr": [
    "ins",
    "del",
    "moveFrom",
    "moveTo",
    "rStyle",
    "rFonts",
    "b",
    "bCs",
    "i",
    "iCs",
    "caps",
    "smallCaps",
    "strike",
    "dstrike",
    "outline",
    "shadow",
    "emboss",
    "imprint",
    "noProof",
    "snapToGrid",
    "vanish",
    "webHidden",
    "color",
    "spacing",
    "w",
    "kern",
    "position",
    "sz",
    "szCs",
    "highlight",
    "u",
    "effect",
    "bdr",
    "shd",
    "fitText",
    "vertAlign",
    "rtl",
    "cs",
    "em",
    "lang",
    "eastAsianLayout",
    "specVanish",
    "oMath",
    "rPrChange",
  ],
  // CT_PPr
  pPr: [
    "pStyle",
    "keepNext",
    "keepLines",
    "pageBreakBefore",
    "framePr",
    "widowControl",
    "numPr",
    "suppressLineNumbers",
    "pBdr",
    "shd",
    "tabs",
    "suppressAutoHyphens",
    "kinsoku",
    "wordWrap",
    "overflowPunct",
    "topLinePunct",
    "autoSpaceDE",
    "autoSpaceDN",
    "bidi",
    "adjustRightInd",
    "snapToGrid",
    "spacing",
    "ind",
    "contextualSpacing",
    "mirrorIndents",
    "suppressOverlap",
    "jc",
    "textDirection",
    "textAlignment",
    "textboxTightWrap",
    "outlineLvl",
    "divId",
    "cnfStyle",
    "rPr",
    "sectPr",
    "pPrChange",
  ],
  // CT_TcPr
  tcPr: [
    "cnfStyle",
    "tcW",
    "gridSpan",
    "hMerge",
    "vMerge",
    "tcBorders",
    "shd",
    "noWrap",
    "tcMar",
    "textDirection",
    "tcFitText",
    "vAlign",
    "hideMark",
    "headers",
    "cellIns",
    "cellDel",
    "cellMerge",
    "tcPrChange",
  ],
  // CT_TrPr: CT_TrPrBase's choice, then the track-change record
  trPr: [
    "cnfStyle",
    "divId",
    "gridBefore",
    "gridAfter",
    "wBefore",
    "wAfter",
    "cantSplit",
    "trHeight",
    "tblHeader",
    "tblCellSpacing",
    "jc",
    "hidden",
    "ins",
    "del",
    "trPrChange",
  ],
  // CT_TblPr
  tblPr: [
    "tblStyle",
    "tblpPr",
    "tblOverlap",
    "bidiVisual",
    "tblStyleRowBandSize",
    "tblStyleColBandSize",
    "tblW",
    "jc",
    "tblCellSpacing",
    "tblInd",
    "tblBorders",
    "shd",
    "tblLayout",
    "tblCellMar",
    "tblLook",
    "tblCaption",
    "tblDescription",
    "tblPrChange",
  ],
  // CT_TcBorders
  tcBorders: [
    "top",
    "start",
    "left",
    "bottom",
    "end",
    "right",
    "insideH",
    "insideV",
    "tl2br",
    "tr2bl",
  ],
  // CT_TblBorders
  tblBorders: [
    "top",
    "start",
    "left",
    "bottom",
    "end",
    "right",
    "insideH",
    "insideV",
  ],
  // CT_PBdr
  pBdr: ["top", "left", "bottom", "right", "between", "bar"],
  // CT_TcMar
  tcMar: ["top", "start", "left", "bottom", "end", "right"],
  // CT_TblCellMar
  tblCellMar: ["top", "start", "left", "bottom", "end", "right"],
  // CT_SdtBlock: CT_SdtRun lays the same three down
  sdt: ["sdtPr", "sdtEndPr", "sdtContent"],
  // CT_SdtPr
  sdtPr: [
    "rPr",
    "alias",
    "tag",
    "id",
    "lock",
    "placeholder",
    "temporary",
    "showingPlcHdr",
    "dataBinding",
    "label",
    "tabIndex",
    "equation",
    "comboBox",
    "date",
    "docPartObj",
    "docPartList",
    "dropDownList",
    "picture",
    "richText",
    "text",
    "citation",
    "group",
    "bibliography",
  ],
  // CT_SectPr
  sectPr: [
    "headerReference",
    "footerReference",
    "footnotePr",
    "endnotePr",
    "type",
    "pgSz",
    "pgMar",
    "paperSrc",
    "pgBorders",
    "lnNumType",
    "pgNumType",
    "cols",
    "formProt",
    "vAlign",
    "noEndnote",
    "titlePg",
    "textDirection",
    "bidi",
    "rtlGutter",
    "docGrid",
    "printerSettings",
    "sectPrChange",
  ],
  // CT_NumPr
  numPr: ["ilvl", "numId", "numberingChange", "ins"],
  // CT_Lvl
  lvl: [
    "start",
    "numFmt",
    "lvlRestart",
    "pStyle",
    "isLgl",
    "suff",
    "lvlText",
    "lvlPicBulletId",
    "legacy",
    "lvlJc",
    "pPr",
    "rPr",
  ],
  // CT_AbstractNum
  abstractNum: [
    "nsid",
    "multiLevelType",
    "tmpl",
    "name",
    "styleLink",
    "numStyleLink",
    "lvl",
  ],
  // CT_Num
  num: ["abstractNumId", "lvlOverride"],
  // CT_Numbering
  numbering: ["numPicBullet", "abstractNum", "num", "numIdMacAtCleanup"],
  // CT_TblStylePr
  tblStylePr: ["pPr", "rPr", "tblPr", "trPr", "tcPr"],
  // CT_Style
  style: [
    "name",
    "aliases",
    "basedOn",
    "next",
    "link",
    "autoRedefine",
    "hidden",
    "uiPriority",
    "semiHidden",
    "unhideWhenUsed",
    "qFormat",
    "locked",
    "personal",
    "personalCompose",
    "personalReply",
    "rsid",
    "pPr",
    "rPr",
    "tblPr",
    "trPr",
    "tcPr",
    "tblStylePr",
  ],
  // CT_Settings
  settings: [
    "writeProtection",
    "view",
    "zoom",
    "removePersonalInformation",
    "removeDateAndTime",
    "doNotDisplayPageBoundaries",
    "displayBackgroundShape",
    "printPostScriptOverText",
    "printFractionalCharacterWidth",
    "printFormsData",
    "embedTrueTypeFonts",
    "embedSystemFonts",
    "saveSubsetFonts",
    "saveFormsData",
    "mirrorMargins",
    "alignBordersAndEdges",
    "bordersDoNotSurroundHeader",
    "bordersDoNotSurroundFooter",
    "gutterAtTop",
    "hideSpellingErrors",
    "hideGrammaticalErrors",
    "activeWritingStyle",
    "proofState",
    "formsDesign",
    "attachedTemplate",
    "linkStyles",
    "stylePaneFormatFilter",
    "stylePaneSortMethod",
    "documentType",
    "mailMerge",
    "revisionView",
    "trackRevisions",
    "doNotTrackMoves",
    "doNotTrackFormatting",
    "documentProtection",
    "autoFormatOverride",
    "styleLockTheme",
    "styleLockQFSet",
    "defaultTabStop",
    "autoHyphenation",
    "consecutiveHyphenLimit",
    "hyphenationZone",
    "doNotHyphenateCaps",
    "showEnvelope",
    "summaryLength",
    "clickAndTypeStyle",
    "defaultTableStyle",
    "evenAndOddHeaders",
    "bookFoldRevPrinting",
    "bookFoldPrinting",
    "bookFoldPrintingSheets",
    "drawingGridHorizontalSpacing",
    "drawingGridVerticalSpacing",
    "displayHorizontalDrawingGridEvery",
    "displayVerticalDrawingGridEvery",
    "doNotUseMarginsForDrawingGridOrigin",
    "drawingGridHorizontalOrigin",
    "drawingGridVerticalOrigin",
    "doNotShadeFormData",
    "noPunctuationKerning",
    "characterSpacingControl",
    "printTwoOnOne",
    "strictFirstAndLastChars",
    "noLineBreaksAfter",
    "noLineBreaksBefore",
    "savePreviewPicture",
    "doNotValidateAgainstSchema",
    "saveInvalidXml",
    "ignoreMixedContent",
    "alwaysShowPlaceholderText",
    "doNotDemarcateInvalidXml",
    "saveXmlDataOnly",
    "useXSLTWhenSaving",
    "saveThroughXslt",
    "showXMLTags",
    "alwaysMergeEmptyNamespace",
    "updateFields",
    "hdrShapeDefaults",
    "footnotePr",
    "endnotePr",
    "compat",
    "docVars",
    "rsids",
    "mathPr",
    "attachedSchema",
    "themeFontLang",
    "clrSchemeMapping",
    "doNotIncludeSubdocsInStats",
    "doNotAutoCompressPictures",
    "forceUpgrade",
    "captions",
    "readModeInkLockDown",
    "smartTagType",
    "schemaLibrary",
    "shapeDefaults",
    "doNotEmbedSmartTags",
    "decimalSymbol",
    "listSeparator",
  ],
};

/**
 * The order the children of this parent go in.
 *
 * A nested parent is asked for first (`pPr/rPr` is CT_ParaRPr, which puts a track-change record
 * ahead of what a run's own `w:rPr` holds), so naming the enclosing element is what picks the
 * right one of two entries for the same element name.
 *
 * Throws for a parent no entry covers, because a writer editing an element this registry has
 * never seen would otherwise place its children by nothing at all.
 */
export function childOrderOf(name: string, parent?: string): readonly string[] {
  const nested =
    parent === undefined ? undefined : CHILD_ORDER[`${parent}/${name}`];
  const order = nested ?? CHILD_ORDER[name];
  if (!order) {
    throw new Error(
      `no child order is registered for ${name}; add it to CHILD_ORDER`
    );
  }
  return order;
}
